export const COUNTRIES = [
  {
    name: "United States",
    code: "US",
    states: [
      { name: "Alabama", code: "AL" },
      { name: "Alaska", code: "AK" },
      { name: "Arizona", code: "AZ" },
      { name: "Arkansas", code: "AR" },
      { name: "California", code: "CA" },
      { name: "Colorado", code: "CO" },
      { name: "Connecticut", code: "CT" },
      { name: "Delaware", code: "DE" },
      { name: "Florida", code: "FL" },
      { name: "Georgia", code: "GA" },
      { name: "Hawaii", code: "HI" },
      { name: "Idaho", code: "ID" },
      { name: "Illinois", code: "IL" },
      { name: "Indiana", code: "IN" },
      { name: "Iowa", code: "IA" },
      { name: "Kansas", code: "KS" },
      { name: "Kentucky", code: "KY" },
      { name: "Louisiana", code: "LA" },
      { name: "Maine", code: "ME" },
      { name: "Maryland", code: "MD" },
      { name: "Massachusetts", code: "MA" },
      { name: "Michigan", code: "MI" },
      { name: "Minnesota", code: "MN" },
      { name: "Mississippi", code: "MS" },
      { name: "Missouri", code: "MO" },
      { name: "Montana", code: "MT" },
      { name: "Nebraska", code: "NE" },
      { name: "Nevada", code: "NV" },
      { name: "New Hampshire", code: "NH" },
      { name: "New Jersey", code: "NJ" },
      { name: "New Mexico", code: "NM" },
      { name: "New York", code: "NY" },
      { name: "North Carolina", code: "NC" },
      { name: "North Dakota", code: "ND" },
      { name: "Ohio", code: "OH" },
      { name: "Oklahoma", code: "OK" },
      { name: "Oregon", code: "OR" },
      { name: "Pennsylvania", code: "PA" },
      { name: "Rhode Island", code: "RI" },
      { name: "South Carolina", code: "SC" },
      { name: "South Dakota", code: "SD" },
      { name: "Tennessee", code: "TN" },
      { name: "Texas", code: "TX" },
      { name: "Utah", code: "UT" },
      { name: "Vermont", code: "VT" },
      { name: "Virginia", code: "VA" },
      { name: "Washington", code: "WA" },
      { name: "West Virginia", code: "WV" },
      { name: "Wisconsin", code: "WI" },
      { name: "Wyoming", code: "WY" },
    ],
  },
  {
    name: "Canada",
    code: "CA",
    states: [
      { name: "Alberta", code: "AB" },
      { name: "British Columbia", code: "BC" },
      { name: "Manitoba", code: "MB" },
      { name: "New Brunswick", code: "NB" },
      { name: "Newfoundland and Labrador", code: "NL" },
      { name: "Nova Scotia", code: "NS" },
      { name: "Ontario", code: "ON" },
      { name: "Prince Edward Island", code: "PE" },
      { name: "Quebec", code: "QC" },
      { name: "Saskatchewan", code: "SK" },
      { name: "Northwest Territories", code: "NT" },
      { name: "Nunavut", code: "NU" },
      { name: "Yukon", code: "YT" },
    ],
  },
  {
    name: "Denmark",
    code: "DK",
    states: [
      { name: "Hovedstaden", code: "84" },
      { name: "Midtjylland", code: "82" },
      { name: "Nordjylland", code: "81" },
      { name: "Sjælland", code: "85" },
      { name: "Syddanmark", code: "83" },
    ],
  },
  {
    name: "Norway",
    code: "NO",
    states: [
      { name: "Viken", code: "30" },
      { name: "Oslo", code: "03" },
      { name: "Innlandet", code: "34" },
      { name: "Vestfold og Telemark", code: "38" },
      { name: "Agder", code: "42" },
      { name: "Rogaland", code: "11" },
      { name: "Vestland", code: "46" },
      { name: "Møre og Romsdal", code: "15" },
      { name: "Trøndelag", code: "50" },
      { name: "Nordland", code: "18" },
      { name: "Troms og Finnmark", code: "54" },
    ],
  },
  {
    name: "Sweden",
    code: "SE",
    states: [
      { name: "Stockholm", code: "AB" },
      { name: "Västra Götaland", code: "O" },
      { name: "Skåne", code: "M" },
      { name: "Uppsala", code: "C" },
      { name: "Södermanland", code: "D" },
      { name: "Östergötland", code: "E" },
      { name: "Jönköping", code: "F" },
      { name: "Kronoberg", code: "G" },
      { name: "Kalmar", code: "H" },
      { name: "Gotland", code: "I" },
      { name: "Blekinge", code: "K" },
      { name: "Halland", code: "N" },
      { name: "Värmland", code: "S" },
      { name: "Örebro", code: "T" },
      { name: "Västmanland", code: "U" },
      { name: "Dalarna", code: "W" },
      { name: "Gävleborg", code: "X" },
      { name: "Västernorrland", code: "Y" },
      { name: "Jämtland", code: "Z" },
      { name: "Västerbotten", code: "AC" },
      { name: "Norrbotten", code: "BD" },
    ],
  },
  {
    name: "Finland",
    code: "FI",
    states: [
      { name: "Uusimaa", code: "18" },
      { name: "Southwest Finland", code: "19" },
      { name: "Satakunta", code: "17" },
      { name: "Kanta-Häme", code: "06" },
      { name: "Pirkanmaa", code: "11" },
      { name: "Päijät-Häme", code: "14" },
      { name: "Kymenlaakso", code: "08" },
      { name: "South Karelia", code: "09" },
      { name: "South Savo", code: "04" },
      { name: "North Savo", code: "13" },
      { name: "North Karelia", code: "12" },
      { name: "Central Finland", code: "08" },
      { name: "South Ostrobothnia", code: "03" },
      { name: "Ostrobothnia", code: "02" },
      { name: "Central Ostrobothnia", code: "16" },
      { name: "North Ostrobothnia", code: "14" },
      { name: "Kainuu", code: "05" },
      { name: "Lapland", code: "07" },
      { name: "Åland Islands", code: "01" },
    ],
  },
  {
    name: "Netherlands",
    code: "NL",
    states: [
      { name: "Drenthe", code: "DR" },
      { name: "Flevoland", code: "FL" },
      { name: "Friesland", code: "FR" },
      { name: "Gelderland", code: "GE" },
      { name: "Groningen", code: "GR" },
      { name: "Limburg", code: "LI" },
      { name: "North Brabant", code: "NB" },
      { name: "North Holland", code: "NH" },
      { name: "Overijssel", code: "OV" },
      { name: "South Holland", code: "ZH" },
      { name: "Utrecht", code: "UT" },
      { name: "Zeeland", code: "ZE" },
    ],
  },
  {
    name: "France",
    code: "FR",
    states: [
      { name: "Auvergne-Rhône-Alpes", code: "ARA" },
      { name: "Bourgogne-Franche-Comté", code: "BFC" },
      { name: "Brittany", code: "BRE" },
      { name: "Centre-Val de Loire", code: "CVL" },
      { name: "Corsica", code: "COR" },
      { name: "Grand Est", code: "GES" },
      { name: "Hauts-de-France", code: "HDF" },
      { name: "Île-de-France", code: "IDF" },
      { name: "Normandy", code: "NOR" },
      { name: "Nouvelle-Aquitaine", code: "NAQ" },
      { name: "Occitanie", code: "OCC" },
      { name: "Pays de la Loire", code: "PDL" },
      { name: "Provence-Alpes-Côte d'Azur", code: "PAC" },
    ],
  },
  {
    name: "Spain",
    code: "ES",
    states: [
      { name: "Andalusia", code: "AN" },
      { name: "Aragon", code: "AR" },
      { name: "Asturias", code: "AS" },
      { name: "Balearic Islands", code: "IB" },
      { name: "Basque Country", code: "PV" },
      { name: "Canary Islands", code: "CN" },
      { name: "Cantabria", code: "CB" },
      { name: "Castile and León", code: "CL" },
      { name: "Castilla-La Mancha", code: "CM" },
      { name: "Catalonia", code: "CT" },
      { name: "Extremadura", code: "EX" },
      { name: "Galicia", code: "GA" },
      { name: "La Rioja", code: "RI" },
      { name: "Madrid", code: "MD" },
      { name: "Murcia", code: "MU" },
      { name: "Navarre", code: "NC" },
      { name: "Valencia", code: "VC" },
    ],
  },
  {
    name: "Germany",
    code: "DE",
    states: [
      { name: "Baden-Württemberg", code: "BW" },
      { name: "Bavaria", code: "BY" },
      { name: "Berlin", code: "BE" },
      { name: "Brandenburg", code: "BB" },
      { name: "Bremen", code: "HB" },
      { name: "Hamburg", code: "HH" },
      { name: "Hesse", code: "HE" },
      { name: "Lower Saxony", code: "NI" },
      { name: "Mecklenburg-Western Pomerania", code: "MV" },
      { name: "North Rhine-Westphalia", code: "NW" },
      { name: "Rhineland-Palatinate", code: "RP" },
      { name: "Saarland", code: "SL" },
      { name: "Saxony", code: "SN" },
      { name: "Saxony-Anhalt", code: "ST" },
      { name: "Schleswig-Holstein", code: "SH" },
      { name: "Thuringia", code: "TH" },
    ],
  },
  {
    name: "United Kingdom",
    code: "GB",
    states: [
      { name: "England", code: "ENG" },
      { name: "Scotland", code: "SCT" },
      { name: "Wales", code: "WLS" },
      { name: "Northern Ireland", code: "NIR" },
    ],
  },
  {
    name: "Italy",
    code: "IT",
    states: [
      { name: "Abruzzo", code: "65" },
      { name: "Aosta Valley", code: "23" },
      { name: "Apulia", code: "75" },
      { name: "Basilicata", code: "77" },
      { name: "Calabria", code: "78" },
      { name: "Campania", code: "72" },
      { name: "Emilia-Romagna", code: "45" },
      { name: "Friuli-Venezia Giulia", code: "36" },
      { name: "Lazio", code: "62" },
      { name: "Liguria", code: "42" },
      { name: "Lombardy", code: "25" },
      { name: "Marche", code: "57" },
      { name: "Molise", code: "67" },
      { name: "Piedmont", code: "21" },
      { name: "Sardinia", code: "88" },
      { name: "Sicily", code: "82" },
      { name: "Trentino-Alto Adige", code: "32" },
      { name: "Tuscany", code: "52" },
      { name: "Umbria", code: "55" },
      { name: "Veneto", code: "34" },
    ],
  },
];
